### ISSUE TITLE
关于Python和Tensorflow版本问题

### ISSUE THREAD

**Issue by picc-lu** [GanjinZero/Tenpai_prediction#4]
Git主你好！
我现在使用的是Python 3.7.7 和 TensorFlow 1.13.1 版本，Win 7系统，但是执行 predict.py 报错了，调试了好长时间仍然不能正常执行，请问下我的这两个版本是否正确？谢谢回复。

**Comment by GanjinZero** [comment]
我是在python3.6和tf1.12上运行的。你可以提供具体的报错信息来看看什么情况。

**Comment by picc-lu** [comment]
因为我的电脑从来没使用过Python和TensorFlow，我感觉好多必需的部件都没安装😂
我目前仅补充安装了 Microsoft Visual C++ 2019 可再发行组件包
![Snipaste_2020-11-17_11-47-16](https://user-images.githubusercontent.com/32639909/99344350-d2cbab80-28ca-11eb-8d07-a7f4bf86adff.png)

Python 3.6.8

requirements.txt
```
numpy==1.14.5
Keras==2.2.4
mahjong==1.1.6
scikit_learn==0.20.3
tensorflow==1.12.0
h5py==2.10.0
```
报错信息
```
"D:\PyCharm workspace\Tenpai_prediction\venv\Scripts\python.exe" "D:/PyCharm workspace/Tenpai_prediction/src/predict.py"
Using TensorFlow backend.
2020-11-17 11:08:51.444947: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _run_fn
    self._extend_graph()
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 1352, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[{{node cu_dnnlstm_1/CudnnRNN}} = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](cu_dnnlstm_1/transpose, cu_dnnlstm_1/ExpandDims_1, cu_dnnlstm_1/ExpandDims_2, cu_dnnlstm_1/concat_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/PyCharm workspace/Tenpai_prediction/src/predict.py", line 6, in <module>
    model = load_model("../model/tenpai.model")
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\saving.py", line 287, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 2470, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 199, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[node cu_dnnlstm_1/CudnnRNN (defined at D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py:922)  = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](cu_dnnlstm_1/transpose, cu_dnnlstm_1/ExpandDims_1, cu_dnnlstm_1/ExpandDims_2, cu_dnnlstm_1/concat_1)]]

Caused by op 'cu_dnnlstm_1/CudnnRNN', defined at:
  File "D:/PyCharm workspace/Tenpai_prediction/src/predict.py", line 6, in <module>
    model = load_model("../model/tenpai.model")
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\layers\recurrent.py", line 532, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\layers\cudnn_recurrent.py", line 90, in call
    output, states = self._process_batch(inputs, initial_state)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\keras\layers\cudnn_recurrent.py", line 517, in _process_batch
    is_training=True)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 1544, in __call__
    input_data, input_h, input_c, params, is_training=is_training)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 1435, in __call__
    seed=self._seed)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 922, in _cudnn_rnn
    outputs, output_h, output_c, _ = gen_cudnn_rnn_ops.cudnn_rnn(**args)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\ops\gen_cudnn_rnn_ops.py", line 144, in cudnn_rnn
    is_training=is_training, name=name)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[node cu_dnnlstm_1/CudnnRNN (defined at D:\PyCharm workspace\Tenpai_prediction\venv\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py:922)  = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](cu_dnnlstm_1/transpose, cu_dnnlstm_1/ExpandDims_1, cu_dnnlstm_1/ExpandDims_2, cu_dnnlstm_1/concat_1)]]


Process finished with exit code 1

```

**Comment by GanjinZero** [comment]
看样子你没有安装cuda，你可以考虑把代码中的所有CudnnLSTM换成LSTM
